name: update-zen-browser

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-zen-browser:
    name: Update Zen Browser
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update hashes and test build
        run: |
          ./update-zen-browser.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "GitHub Action automated Zen update"
          file_pattern: '*'
